name: Renovate
on:

  pull_request:
    branches:
      - main   

  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
